# Generated by Django 5.0.4 on 2024-04-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=200)),
                ("disease", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("report_date", models.DateField()),
                ("reason_for_visit", models.CharField(max_length=200)),
                ("diagnosis", models.CharField(max_length=200)),
                ("treatment_plan", models.CharField(max_length=200)),
                ("medications_prescribed", models.CharField(max_length=200)),
                ("follow_up_instructions", models.CharField(max_length=200)),
                ("next_steps", models.CharField(max_length=200)),
                ("follow_up_appointment_schedule", models.DateTimeField()),
            ],
        ),
    ]
